name: test-vth

on:
    workflow_dispatch:
    pull_request:
      branches:
        - main
        - '[0-9]*.[0-9]*.[0-9]*-nightly'

jobs:
  test-vth-amd64:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/test-app.yaml@0.11.0-nightly
    with:
      APP_NAME: vth
      WORKFLOW_AGENT: ubuntu-latest
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}
      

  test-vth-arm64:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/test-app.yaml@0.11.0-nightly
    with:
      APP_NAME: vth
      WORKFLOW_AGENT: spacesdk-ubuntu-2204LTS-arm64
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}
